[build]
  base = "/"       # Adjust this to the directory where your source code is located
  publish = "/"  # Directory where your built files are stored after running the build command
  command = "npm run build"  # Command to build your site

[build.environment]
  NODE_VERSION = "18"  # Define the Node.js version to use

[dev]
  framework = "vite"  # Specify the framework used for local development
